index:
    path: /
    controller: App\Controller\DefaultController::index

#app_test:
#  path: /test
#  controller: App\Controller\TestController::number    --> dans testController utilise annotations --> testeur
